replicaCount: 2

image:
  repository: oneops/controlplane
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  ONEOPS_ENV: dev
  ONEOPS_HTTP_ADDR: ":8080"

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
